language: python
python:
   - "3.6"

install:
   - pip install -U pip

before_script:
   - pip install -r requirements.txt

script:
   - coverage run TestPassChecker.py
   - coverage run TestLongerString.py

after_success:
   - coveralls
   - coverge report