language: python
python:
   - "3.6"

install:
   - pip install -U pip

before_script:
   - pip install -r requirements.txt

script:
   - python TestPassChecker.py
   - python TestLongerString.py

after_success:
   - coveralls